# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
mysql: &mysql
  adapter: mysql2
  username: travis
  database: granted_<%= Rails.env %>

postgresql: &postgresql
  adapter: postgresql
  username: travis
  database: granted_<%= Rails.env %>
  min_messages: ERROR

defaults: &defaults
  pool: 16
  timeout: 5000
  host: localhost
  <<: *<%= ENV['DB'] || "mysql" %>

development:
  <<: *defaults

test:
  <<: *defaults
